[package]
name = "trsws"
version = "0.1.0"
authors = ["nick-ccc"]
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "trsws"

[dependencies]
actix-web = "^4.13.0"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
serde = {version = "1", features = ["derive"]}
config = { version = "0.14", default-features = false, features = ["yaml"] }
sqlx = { version = "0.8.6", default-features = false, features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
] }
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4.22", default-features = false, features = ["clock"] }
anyhow = "1.0.103"
serde-aux = "4.7.0"
tracing = "0.1.44"
thiserror = "2.0.18"

[dev-dependencies]
reqwest = "0.13"
